import { Advisor, TeamPerformancePoint } from './types';

export const TEAM_PERFORMANCE_DATA: TeamPerformancePoint[] = [
  { x: 'Jan', y: 8.1 },
  { x: 'Feb', y: 8.4 },
  { x: 'Mar', y: 8.2 },
  { x: 'Apr', y: 8.7 },
  { x: 'May', y: 8.9 },
  { x: 'Jun', y: 9.1 },
];

export const MOCK_ADVISORS: Advisor[] = [
  {
    id: 'sj',
    initials: 'SJ',
    avatarColor: 'bg-blue-500',
    name: 'Sarah Johnson',
    title: 'Senior Financial Advisor',
    clients: 47,
    aum: 12.8e6,
    performanceScore: 9.2,
    communicationScore: 'Excellent',
    taskCompletion: 94,
    clientSatisfaction: 4.8,
    newClientsYTD: 8,
    avgResponse: '1.8h',
    clientRetention: 96,
  },
  {
    id: 'mc',
    initials: 'MC',
    avatarColor: 'bg-purple-500',
    name: 'Michael Chen',
    title: 'Senior Financial Advisor',
    clients: 42,
    aum: 11.2e6,
    performanceScore: 8.7,
    communicationScore: 'Good',
    taskCompletion: 89,
    clientSatisfaction: 4.6,
    newClientsYTD: 6,
    avgResponse: '2.1h',
    clientRetention: 92,
  },
  {
    id: 'er',
    initials: 'ER',
    avatarColor: 'bg-pink-500',
    name: 'Emily Rodriguez',
    title: 'Financial Advisor',
    clients: 31,
    aum: 5.7e6,
    performanceScore: 8.1,
    communicationScore: 'Excellent',
    taskCompletion: 85,
    clientSatisfaction: 4.7,
    newClientsYTD: 5,
    avgResponse: '2.3h',
    clientRetention: 93,
  },
  {
    id: 'dw',
    initials: 'DW',
    avatarColor: 'bg-indigo-500',
    name: 'David Wilson',
    title: 'Junior Financial Advisor',
    clients: 18,
    aum: 3.4e6,
    performanceScore: 7.3,
    communicationScore: 'Average',
    taskCompletion: 78,
    clientSatisfaction: 4.1,
    newClientsYTD: 9,
    avgResponse: '3.2h',
    clientRetention: 95,
  },
];