import { Client } from './types';

export const MOCK_CLIENTS: Client[] = [
  {
    id: 1,
    initials: 'JD',
    name: 'John & Jane Doe',
    primaryAdvisor: 'Robert McMillan',
    totalAUM: 1350000,
    annualFees: 9450,
    feeRate: 0.7,
    spouse: 'Jane Doe',
    email: 'john.doe@example.com',
    phone: '+1 (555) 123-4567',
    address: '123 Market Street, San Francisco, CA',
    riskProfile: 'Balanced',
    avatarColor: 'bg-purple-500',
    contactSince: '2019',
    accounts: [
      { name: 'Individual', value: 450000 },
      { name: 'Joint', value: 650000 },
      { name: 'IRA', value: 250000 },
    ],
    recentActivity: [
      { title: 'Reviewed IPS', time: '2 days ago', icon: 'check' },
      { title: 'Uploaded W-2', time: '1 week ago', icon: 'doc' },
      { title: 'Synced custodian feed', time: '3 weeks ago', icon: 'sync' },
    ],
    healthScoreBreakdown: [
      { category: 'Portfolio', score: 88 },
      { category: 'Engagement', score: 76 },
      { category: 'Compliance', score: 92 },
      { category: 'Risk', score: 81 },
    ],
    nextActions: [
      { title: 'Schedule Q4 review' },
      { title: 'Confirm beneficiary designations' },
    ],
    healthScore: 86,
    lastContact: '3 days ago',
  },
  {
    id: 2,
    initials: 'AS',
    name: 'Alice & Bob Smith',
    primaryAdvisor: 'Emily Clarke',
    totalAUM: 2480000,
    annualFees: 17360,
    feeRate: 0.7,
    spouse: 'Bob Smith',
    email: 'alice.smith@example.com',
    phone: '+1 (555) 987-6543',
    address: '456 River Road, Austin, TX',
    riskProfile: 'Growth',
    avatarColor: 'bg-blue-500',
    contactSince: '2017',
    accounts: [
      { name: 'Joint', value: 950000 },
      { name: 'Trust', value: 830000 },
      { name: 'Roth IRA', value: 700000 },
    ],
    recentActivity: [
      { title: 'Tax documents received', time: 'yesterday', icon: 'doc' },
      { title: 'Portfolio rebalanced', time: '5 days ago', icon: 'check' },
      { title: 'Custodian sync', time: '2 weeks ago', icon: 'sync' },
    ],
    healthScoreBreakdown: [
      { category: 'Portfolio', score: 93 },
      { category: 'Engagement', score: 68 },
      { category: 'Compliance', score: 95 },
      { category: 'Risk', score: 74 },
    ],
    nextActions: [
      { title: 'Plan charitable giving strategy' },
      { title: 'Update CFP plan' },
    ],
    healthScore: 90,
    lastContact: '1 day ago',
  },
  {
    id: 3,
    initials: 'MT',
    name: 'Michael & Tina Lopez',
    primaryAdvisor: 'Robert McMillan',
    totalAUM: 820000,
    annualFees: 5740,
    feeRate: 0.7,
    spouse: 'Tina Lopez',
    email: 'michael.lopez@example.com',
    phone: '+1 (555) 222-3344',
    address: '789 Sunset Ave, Denver, CO',
    riskProfile: 'Conservative',
    avatarColor: 'bg-amber-500',
    contactSince: '2021',
    accounts: [
      { name: 'Individual', value: 320000 },
      { name: 'Joint', value: 380000 },
      { name: 'SEP IRA', value: 120000 },
    ],
    recentActivity: [
      { title: 'Updated risk questionnaire', time: '4 days ago', icon: 'check' },
      { title: 'Uploaded pay stubs', time: '2 weeks ago', icon: 'doc' },
    ],
    healthScoreBreakdown: [
      { category: 'Portfolio', score: 72 },
      { category: 'Engagement', score: 61 },
      { category: 'Compliance', score: 88 },
      { category: 'Risk', score: 69 },
    ],
    nextActions: [
      { title: 'Schedule annual review' },
    ],
    healthScore: 71,
    lastContact: '1 week ago',
  },
  {
    id: 4,
    initials: 'MW',
    name: 'Michael Williams',
    primaryAdvisor: 'Michael Chen',
    totalAUM: 1800000,
    annualFees: 12600,
    feeRate: 0.7,
    spouse: '—',
    email: 'michael.williams@example.com',
    phone: '+1 (555) 410-7890',
    address: '2418 Bay Road, Seattle, WA',
    riskProfile: 'Growth',
    avatarColor: 'bg-violet-500',
    contactSince: '2018',
    accounts: [
      { name: 'Individual', value: 900000 },
      { name: 'Trust', value: 600000 },
      { name: 'Roth IRA', value: 300000 },
    ],
    recentActivity: [
      { title: 'Quarterly review completed', time: '1 week ago', icon: 'check' },
      { title: 'Statement uploaded', time: '3 days ago', icon: 'doc' },
    ],
    healthScoreBreakdown: [
      { category: 'Portfolio', score: 80 },
      { category: 'Engagement', score: 72 },
      { category: 'Compliance', score: 90 },
      { category: 'Risk', score: 65 },
    ],
    nextActions: [
      { title: 'Discuss tax-loss harvesting' },
    ],
    healthScore: 78,
    lastContact: '1 week ago',
  },
  {
    id: 5,
    initials: 'LM',
    name: 'Lisa Martinez',
    primaryAdvisor: 'Emily Rodriguez',
    totalAUM: 3100000,
    annualFees: 21700,
    feeRate: 0.7,
    spouse: '—',
    email: 'lisa.martinez@example.com',
    phone: '+1 (555) 610-3434',
    address: '77 Grand Ave, Miami, FL',
    riskProfile: 'Balanced',
    avatarColor: 'bg-pink-500',
    contactSince: '2020',
    accounts: [
      { name: 'Joint', value: 1500000 },
      { name: 'Trust', value: 1100000 },
      { name: 'IRA', value: 500000 },
    ],
    recentActivity: [
      { title: 'Reviewed IPS', time: '3 days ago', icon: 'check' },
      { title: 'Uploaded K-1', time: '1 week ago', icon: 'doc' },
    ],
    healthScoreBreakdown: [
      { category: 'Portfolio', score: 95 },
      { category: 'Engagement', score: 85 },
      { category: 'Compliance', score: 92 },
      { category: 'Risk', score: 78 },
    ],
    nextActions: [
      { title: 'Prepare Q3 investment report' },
    ],
    healthScore: 95,
    lastContact: '3 days ago',
  },
];